name: geopolitical-fuel-forecast

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
      - yfinance
      - fredapi